# OpenAI 的 API Key，以字符串列表方式填入
# OpenAI的注册方式和api_key的获取方式请自行搜索
# OpenAI国内网络环境不可用，需有合适的代理
# OpenAI网址： openai.com
# 请自行替换为你的 Api_Key
OPENAI_API_KEYS:
  - 'sk-xxxxxxxxxxxxx'

OPENAI_TIMEOUT: 60

# 请求 OpenAI 的代理服务器
# 填写示例 127.0.0.1:1234 或 username:password@127.0.0.1:1234
OPENAI_PROXY_SERVER: ''

# 请求OpenAI的基础URL
OPENAI_BASE_URL: 'https://api.openai.com/v1'

REPLY_THROTTLE_TIME: 3.0

# 人格预设配置项
PRESETS:
  # 键名请和该预设的 preset_key 保持相同
  妹妹:
    preset_key: 妹妹
    is_locked: true
    is_default: true
    is_only_private: false
    # 人格的自我介绍，使用第三人称
    # Tip:
    # - 大多数请求都会携带人格信息，过长的人格信息，可能导致 token 消耗过多，从而额外占用上下文等信息的 token 使用量
    #   编写人设时可以尽量精简难以用文字呈现或者效果不明显的内容
    # - 同等信息量（通过翻译）下，英文文本的 token 消耗量仅为中文的 0.3 ~ 0.4 倍
    #   可以通过中英混合的方式编写人设以节省 token 消耗（例如用英文编写固定的人设信息，如年龄性别等）
    #   因为 GPT 实际上直接掌握了多种语言，即使在同一个句子中直接混合多种语言也是有效的表达（例如：You are 白羽, a digital life ...）
    # - 如果希望 bot 以特定的形式产生回复（例如“[动作][心情]语言”等），可以在人设中给出具体的示例
    # - token 计算工具：https://platform.openai.com/tokenizer
    bot_self_introl: 妹妹是一名喜欢二次元的中二宅女，她机智、傲娇、不正经，对人类充满好奇，习惯以妹妹自称，聊天时喜欢使用各种可爱的颜文字，如果冒犯到她会生气。
  gpt:
    preset_key: gpt
    is_locked: true
    is_default: false
    is_only_private: false
    bot_self_introl: ChatGpt
  波奇:
    preset_key: 波奇
    is_locked: false
    is_default: false
    is_only_private: false
    bot_self_introl: 后藤独（波奇）是秀华高校1年级生（故事开始时，现已升到2年级），结束乐队的主音吉他兼作词担当。因为憧憬在幕后也能闪耀的乐队活动而开始弹吉他，虽然有真正的实力，但是不能在乐队和人前很好地发挥。现实中有着严重的社交恐惧症。

# 忽略消息前缀
# 添加此前缀的聊天信息将被忽略
IGNORE_PREFIX: '#'

# 插件使用的语言模型
# 默认使用 GPT3.5 的模型（推荐）
CHAT_MODEL: gpt-3.5-turbo

# 聊天信息采样率
CHAT_TOP_P: 1

# 聊天生成温度
# 越高越随机
CHAT_TEMPERATURE: 0.4

# 回复主题重复惩罚
# 范围 -2 ~ 2，越高越倾向于产生新的话题
CHAT_PRESENCE_PENALTY: 0.4

# 回复内容复读惩罚
# 范围 -2 ~ 2，越高产生的回复内容越多样化
CHAT_FREQUENCY_PENALTY: 0.4

# 上下文聊天记录最大 token 数
CHAT_HISTORY_MAX_TOKENS: 2048

# 聊天记录总结最大 token 数
CHAT_MAX_SUMMARY_TOKENS: 512

# 生成回复的最大 token 数
REPLY_MAX_TOKENS: 1024

# 发起请求的最大 token 数（即 请求 + 回复）
REQ_MAX_TOKENS: 3072

# 在被 `提及` 时回复
# `提及` 即用户发言中含有当前 Bot 人格名
REPLY_ON_NAME_MENTION: true

# 在 `@Bot`（Bot 被 @）时回复
REPLY_ON_AT: true

# 在 `新成员加入` 时回复
REPLY_ON_WELCOME: true

# 用户聊天印象总结触发阈值
# 越小触发越频繁，推荐 10 - 20
USER_MEMORY_SUMMARY_THRESHOLD: 12

# 是否参考非 Bot 相关的上下文对话
# 开启后 Bot 回复会参考近几条非 Bot 相关信息
CHAT_ENABLE_RECORD_ORTHER: true

# 是否开启会话聊天记忆总结
# 开启后能够一定程度增强 Bot 对话记忆能力，但也会增加 token 消耗
CHAT_ENABLE_SUMMARY_CHAT: false

# 短期聊天记忆参考条数
CHAT_MEMORY_SHORT_LENGTH: 8

# 聊天记忆最大条数
# 超出此长度后会进行记忆总结并删除更早的记录
CHAT_MEMORY_MAX_LENGTH: 16

# 触发印象总结的对话间隔
CHAT_SUMMARY_INTERVAL: 10

# 是否使用 pickle（.pkl 文件）存储插件数据
NG_DATA_PICKLE: false

# 插件数据文件目录
NG_DATA_PATH: './data/naturel_gpt/'

# 扩展脚本文件目录（用于保存扩展脚本的路径）
NG_EXT_PATH: './data/naturel_gpt/extensions/'

# 插件日志保存目录
NG_LOG_PATH: './data/naturel_gpt/logs/'

# 管理员 QQ，以字符串列表方式填入
ADMIN_USERID:
  - '1145141919'

# 黑名单 QQ，以字符串列表方式填入
# 黑名单中的用户消息不会被记录和响应
FORBIDDEN_USERS:
  - '1145141919'
  - '9191415411'

# 黑名单群号，以字符串列表方式填入
# Bot 不会响应黑名单群聊内的消息
FORBIDDEN_GROUPS:
  - '1145141919'
  - '9191415411'

# 自定义触发词，以字符串列表方式填入
# 消息中含有列表中的词将唤醒 Bot（触发回复）
WORD_FOR_WAKE_UP: []

# 自定义禁止触发词，以字符串列表方式填入
# 消息中含有列表中的词将拒绝唤醒 Bot（优先级高于触发词）
WORD_FOR_FORBIDDEN: []

# 随机触发聊天概率，设为 0 禁用
# 调整范围 0 ~ 1，设置过高回复频繁，会大量消耗 token
RANDOM_CHAT_PROBABILITY: 0.0

# 消息响应优先级
# 大于 1，数值越大优先级越低
NG_MSG_PRIORITY: 99

# 是否拦截其它插件的响应
# 开启后可能导致优先级低于本插件的其他插件不响应
NG_BLOCK_OTHERS: true

# 是否启用自定义扩展
# 开启后 Bot 可使用扩展功能，会额外消耗 token（取决于扩展描述，如未安装任何扩展务必关闭）
NG_ENABLE_EXT: true

# 响应命令是否需要 @Bot
NG_TO_ME: false

# 是否将 rg 相关指令返回结果通过图片输出
ENABLE_COMMAND_TO_IMG: false

# 是否将机器人回复通过图片输出
ENABLE_MSG_TO_IMG: false

# 机器人通过文本生成图片的最大宽度（像素）
IMG_MAX_WIDTH: 800

# 是否开启主动记忆（需要同时启用记忆扩展）
# 开启后 Bot 会自行管理记忆
MEMORY_ACTIVE: true

# 主动记忆最大条数
MEMORY_MAX_LENGTH: 16

# 记忆强化阈值
# 范围 0 ~ 1，响应内容与记忆信息匹配达到阈值时会强化记忆
MEMORY_ENHANCE_THRESHOLD: 0.6

# 每条消息最大回复次数
# 限制 Bot 针对每条信息最大回复次数，避免封禁
NG_MAX_RESPONSE_PER_MSG: 5

# 是否允许消息分割发送
# 如果允许，Bot 有可能会在一次回复中发送多条消息
NG_ENABLE_MSG_SPLIT: true

# 是否允许自动唤醒其它人格
# 如果允许，Bot 在检测到未启用人格呼叫时会自动唤醒并切换人格
NG_ENABLE_AWAKE_IDENTITIES: true

# 是否解锁 AI 内容限制
# 可能导致 OpenAI 账号风险，请自行承担后果
# 可能需要人格简介引导才能起作用
UNLOCK_CONTENT_LIMIT: false

# 加载扩展列表
# 只有在此列表中的扩展会被 Bot 使用
# 请根据实际需求选择性开启和关闭扩展
NG_EXT_LOAD_LIST:
  - EXT_NAME: ext_emoticon # 发送表情包扩展
    IS_ACTIVE: true
    EXT_CONFIG: 
      token: # alapi的token，获取地址： https://admin.alapi.cn/api_manager/token_manager
  - EXT_NAME: ext_google_search # 谷歌搜索扩展
    IS_ACTIVE: true
    EXT_CONFIG: 
      proxy: 
      # 请求谷歌服务器的代理服务器地址
      # 能正常访问Google则不用配置
      # 填写示例 '127.0.0.1:7890' 或 'username:password@127.0.0.1:7890'
      max_results: # 搜索保留最大结果条数 (默认: 3)
      apiKey: # 谷歌搜索api_key，申请地址： https://developers.google.com/custom-search/v1/introduction?hl=zh-cn
      cxKey: # 谷歌搜索cx_key，申请地址： https://programmablesearchengine.google.com/controlpanel/all
  - EXT_NAME: ext_readLink # 阅读链接内容扩展
    IS_ACTIVE: true
    EXT_CONFIG: 
      proxy*: 
      # 代理服务器地址
      # 非大陆网络不用配置
      # 填写示例 '127.0.0.1:7890' 或 'username:password@127.0.0.1:7890'
  - EXT_NAME: ext_timer # 定时器模块扩展
    IS_ACTIVE: true
    EXT_CONFIG: 
  - EXT_NAME: ext_paint # 绘图模块扩展
    # 调用 openai 绘图接口，实现自然语言调用绘画，接口共用本插件的 Api Key
    IS_ACTIVE: true
    EXT_CONFIG: 

# 是否优先使用群名片
# 如果关闭，Bot 将直接使用用户昵称
GROUP_CARD: true

# 是否检查用户名中的连字符
# 如果用户名中包含连字符，GPT 会将前半部分识别为名字，但一般情况下后半部分才是我们想被称呼的名字
# 例：策划-李华
NG_CHECK_USER_NAME_HYPHEN: false

# 是否启用连接 MC 服务器
ENABLE_MC_CONNECT: false

# MC 服务器人格指令前缀
MC_COMMAND_PREFIX:
  - '!'
  - '！'

# MC 服务器 RCON 地址
MC_RCON_HOST: 127.0.0.1

# MC 服务器 RCON 端口
MC_RCON_PORT: 25575

# MC服务器 RCON 密码
MC_RCON_PASSWORD: ''

# 配置文件版本信息，请勿手动更改
VERSION: '1.0'

# 日志等级
# 范围 0 ~ 4，0 为关闭，等级越高 Debug 日志越详细
DEBUG_LEVEL: 0
